using Jellyfin.Plugin.GuruAudioEnhancer.Services;
using MediaBrowser.Model.Tasks;

namespace Jellyfin.Plugin.GuruAudioEnhancer.ScheduledTasks;

public sealed class CleanupEnhancedAudioTask : IScheduledTask, IConfigurableScheduledTask
{
    private readonly AudioEnhancerService _service;

    public CleanupEnhancedAudioTask(AudioEnhancerService service) => _service = service;

    public string Name => "Remove generated enhanced audio";
    public string Key => "GuruAudioEnhancerCleanup";
    public string Description => "Deletes sidecar audio files generated by Guru Audio Enhancer.";
    public string Category => "Guru Audio Enhancer";
    public bool IsHidden => false;
    public bool IsEnabled => true;
    public bool IsLogged => true;

    public Task ExecuteAsync(IProgress<double> progress, CancellationToken cancellationToken)
        => _service.CleanupAsync(progress, cancellationToken);

    public IEnumerable<TaskTriggerInfo> GetDefaultTriggers() => Array.Empty<TaskTriggerInfo>();
}
