name: Feature request
description: Suggest an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behaviour
      description: Describe how you would expect it to work in Jellyfin.
    validations:
      required: true
